### ISSUE TITLE
material-ui errors

### ISSUE THREAD

**Issue by mcalfin** [oliviertassinari/SplitMe#36]
Hello!

Is there any specific version of material-ui-next that needs to be installed for this to work? I'm trying to run npm run server:development and I'm running into the following issue

/opt/SplitMe/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

Error: /opt/SplitMe/src/main/snackbar/Snackbar.js: Can't resolve 'material-ui/Snackbar' in '/opt/SplitMe/src/main/snackbar'
    at onResolved (/opt/SplitMe/node_modules/enhanced-resolve/lib/Resolver.js:66:16)
    at loggingCallbackWrapper (/opt/SplitMe/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/opt/SplitMe/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/opt/SplitMe/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/opt/SplitMe/node_modules/tapable/lib/Tapable.js:245:46)
    at innerCallback (/opt/SplitMe/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/opt/SplitMe/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /opt/SplitMe/node_modules/tapable/lib/Tapable.js:347:15
    at innerCallback (/opt/SplitMe/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/opt/SplitMe/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)

Any help appreciated!

**Comment by mcalfin** [comment]
nevermind! got it working... great app but the lack of central db made it difficult to share it with roommates.

**Comment by oliviertassinari** [comment]
@mcalfin :)
